### ISSUE TITLE
$http.post() is not working

### ISSUE THREAD

**Issue by shadowzer** [shadowzer/web-backend#1]
I tried 1st & 3rd variants from [this question](http://stackoverflow.com/questions/19254029/angularjs-http-post-does-not-send-data) but both of it is not working.

Anyway POST request is working well from REST client. 
It's getting code 200 (OK) from $http.post but data files don't update.

search issue in /js/app.js via `//todo $HTTP.POST IS NOT WORKING`

**Comment by cjbars** [comment]
$_POST array is emty in UsersController
try php://input

**Comment by shadowzer** [comment]
fixed
